spring:
  datasource:
    url: jdbc:presto://presto-master:8080/hive/tpch_100gb
    username: hdfs
    password: na
    driver-class-name: com.facebook.presto.jdbc.PrestoDriver

benchmark-service:
  url: http://localhost:8080

environment:
  name: DEFAULT