benchmark-service:
  url: http://hadoop-r3n1.td.teradata.com:18080

data-sources:
  presto:
    url: jdbc:presto://10.25.17.79:8090
    username: hdfs
    password: na
    driver-class-name: com.facebook.presto.jdbc.PrestoDriver

environment:
  name: CDH

presto:
  url: http://10.25.17.79:8090

graphite:
  url: http://10.25.17.79:18088
  resolution.seconds: 10
  metrics:
    cpu: asPercent(sumSeries(collectd.hadoop-r3*.cpu.percent-{user,system}.value), sumSeries(collectd.hadoop-r3*.cpu.*.value))
    memory: collectd.hadoop-r3*.memory
    network: sumSeries(collectd.hadoop-r3*.interface-*.if_octets.{rx,tx})

macros:
  drop-caches:
    command: hfab -R all other:presto_hdp_perf_cluster node.shell:"echo 3 > /proc/sys/vm/drop_caches"

benchmark:
  feature:
    graphite:
      event.reporting.enabled: true
      metrics.collection.enabled: true
    presto:
      metrics.collection.enabled: true